# Generated by Django 3.2.13 on 2023-04-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230421_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_stock',
            field=models.BooleanField(default=True),
        ),
    ]
